# Generated by Django 2.0 on 2018-04-22 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180418_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date_of_contract', models.DateField(null=True)),
                ('organiser', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(user_type=1), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organiser', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(user_type=2), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
