# Generated by Django 2.0 on 2018-04-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('proshow', 'proshow'), ('catering', 'catering'), ('logistics', 'logistics')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
